#!/usr/bin/env python3
"""Module for asynchronous list comprehension."""

import asyncio
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Return a list of 10 random floats between 0 and 10
    generated by async_generator using an async comprehension.
    """
    return [i async for i in async_generator()]
